### ISSUE TITLE
Smart contract support

### ISSUE THREAD

**Issue by chris13524** [WalletConnect/notify-server#145]
See: https://www.notion.so/walletconnect/Notify-API-the-road-to-chain-agnostic-smart-contract-wallets-ff76440cad164b91a9bbfbb19b95b1da?pvs=4

**Comment by chadyj** [comment]
@chris13524 Is this going to happen for launch? Or will it come later?

**Comment by chris13524** [comment]
> Is this going to happen for launch? Or will it come later?

I might be able to squeeze it in tomorrow or over the weekend

**Comment by chris13524** [comment]
Support should be ready in backend, but JS client will actually need an update to support smart contract signatures: https://github.com/orgs/WalletConnect/projects/30/views/1?pane=issue&itemId=52286665
