### ISSUE TITLE
fix: handler functions do not anticipate websocket disconnection

### ISSUE THREAD

**Issue by chris13524** [WalletConnect/notify-server#74]
Error example:
```
Error handling notify subscribe: Websocket client error: Connection closed: Disconnecting for load balancing reasons (4010)
```

**Comment by geekbrother** [comment]
As a possible easy solution, we can use a retrying loop with some max attempts and regenerate the connection (Client) when checking the type of error [here](https://github.com/WalletConnect/notify-server/blob/3e8ad15df608bbb50557dc9c7eb2d6a6cf41d087/src/websocket_service/mod.rs#L135) for example (same for all tags). In this case, we can wrap the Client with a re-generation logic to make it work.
What do you think @chris13524 ?

**Comment by chris13524** [comment]
@geekbrother I think it would be better to handle the error and do the retry at the point of each publish (for example [here](https://github.com/WalletConnect/notify-server/blob/3e8ad15df608bbb50557dc9c7eb2d6a6cf41d087/src/websocket_service/handlers/notify_subscribe.rs#L170)), rather than the handler function after the entire request has basically failed. Doing it at your suggested point depends on request idempotency which we should have, but I'd prefer the problem to be handled closer to its source.
